# Generated by Django 5.1.3 on 2025-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_ativacao_token_alter_ativacao_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativacao',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
