# Generated by Django 5.1.3 on 2025-02-22 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_alter_ativacao_token_expiration_resetsenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativacao',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 20, 45, 14, 359549, tzinfo=datetime.timezone.utc)),
        ),
    ]
